version: '3.4'

services:
  db:
    image: postgres
    restart: always
    container_name: jpa_rockstars_db
    network_mode: bridge
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: jpa_demo
    volumes:
      - ./create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

